In [55]:
import numpy as np

In [56]:
A_raw = np.array([[1, 1, 1, 1], [1, -1, 1, -1]], dtype=np.float64)

In [57]:
Tmax = np.array([50, 50, 200, 200])
Tcmd = 300 
dT = 200

A_norm = A_raw * Tmax 
goal = np.array([Tcmd, dT], dtype=np.float64)

In [58]:
B = np.linalg.pinv(A_norm)
res_norm = B @ goal
res = res_norm * Tmax
print(res_norm, sum(res_norm))
print(res, sum(res))
print(A_norm @ res_norm)
print(A_raw @ res)

[0.29411765 0.05882353 1.17647059 0.23529412] 1.7647058823529416
[ 14.70588235   2.94117647 235.29411765  47.05882353] 300.0
[300. 200.]
[300. 200.]


In [59]:
res_soft_max = np.exp(res_norm) / np.sum(np.exp(res_norm))
print(res_soft_max, sum(res_soft_max))

[0.19418265 0.15347    0.46925774 0.18308961] 1.0
